### ISSUE TITLE
[Feature] Add json format output in report

### ISSUE THREAD

**Issue by BoynChan** [ddosify/ddosify#22]
I have seen that we use some kind of formatted string for report output. I wonder if we can use json format (add a flag for configuring or sth.) for report output.
I think structure will like below
`[
    { // Step 1
        "success_count":17,
        "failed_count":3,
        "duration":{
            "dns":0.0007
            // etc.. 
        },
        "status_code":{
            "200":17
        },
        "error_distribution":{
            "connection_timeout":3
        }
    },
    {
        // Step 2 things
    }
]`

And also I think it's time to refactor using template as the code writted https://github.com/ddosify/ddosify/blob/master/core/report/stdout.go#L168

**Comment by kursataktas** [comment]
Hi @BoynChan 

- JSON formatted output would be great, I agree with you.  Printing JSON to the stdout might be a bit weird. JSON file export as an output seems more logical to me. Specifically for what reason do you need this? I'm asking this because maybe we can add a more generic feature that solves more peoples' requirements.
- Yes, we need to refactor there :) TBH it has the least priority currently, but we'll refactor it sooner or later.

**Comment by BoynChan** [comment]
Thx @kursataktas .

**Comment by kursataktas** [comment]
This would be a great feature. I've added this to our roadmap.

**Comment by kursataktas** [comment]
Hi @BoynChan 

JSON formatted output added with [PR](https://github.com/ddosify/ddosify/pull/38) and available on [ Ddosify 0.7.0](https://github.com/ddosify/ddosify/releases/tag/0.7.0)
